"use client";

import { usePlayground } from "@/lib/store";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
  DropdownMenuGroup,
  DropdownMenuLabel,
} from "@/components/ui/dropdown-menu";
import { templates } from "@/lib/templates";
import { toast } from "sonner";
import {
  Play,
  RotateCcw,
  ChevronDown,
  Code2,
  ClipboardCopy,
  Sparkles,
  Braces,
  Activity,
} from "lucide-react";
import { useCallback } from "react";

export default function Header() {
  const { state, dispatch, setCode, runCode, clearAll } = usePlayground();

  const handleRun = useCallback(() => {
    if (!state.code.trim()) {
      toast.error("No code to run", {
        description: "Write some JavaScript code first.",
      });
      return;
    }
    runCode();
    toast.success("Code executing...", {
      description: "Check the output preview and panels below.",
      duration: 2000,
    });
  }, [state.code, runCode]);

  const handleReset = useCallback(() => {
    clearAll();
    toast.info("Playground reset", { duration: 1500 });
  }, [clearAll]);

  const handleTemplateSelect = useCallback(
    (templateId: string) => {
      const template = templates.find((t) => t.id === templateId);
      if (template) {
        setCode(template.code);
        clearAll();
        toast.success(`Loaded: ${template.name}`, {
          description: template.description,
          duration: 2000,
        });
      }
    },
    [setCode, clearAll]
  );

  const handleCopyReport = useCallback(() => {
    const bugs = state.analysis?.bugs || [];
    const suggestions = state.analysis?.suggestions || [];
    const logs = state.consoleLogs;
    const errors = state.errors;
    const events = state.eventLogs;
    const perf = state.performance;

    const report = `═══════════════════════════════════════
  JS Debug Playground — Debug Report
═══════════════════════════════════════

📊 PERFORMANCE
━━━━━━━━━━━━━━
${perf ? `Execution Time: ${perf.executionTime}ms
DOM Mutations: ${perf.domMutationCount}
Event Listeners: ${perf.eventCount}` : "No performance data"}

❌ ERRORS (${errors.length})
━━━━━━━━━━━━━━
${errors.length > 0 ? errors.map((e) => `• ${e.message}${e.line ? ` (line ${e.line})` : ""}`).join("\n") : "No errors"}

⚠️ BUGS DETECTED (${bugs.length})
━━━━━━━━━━━━━━
${bugs.length > 0 ? bugs.map((b) => `• [${b.severity.toUpperCase()}] ${b.title}: ${b.description}`).join("\n") : "No bugs detected"}

🖥️ CONSOLE OUTPUT (${logs.length} messages)
━━━━━━━━━━━━━━
${logs.length > 0 ? logs.map((l) => `[${l.level.toUpperCase()}] ${l.args.join(" ")}`).join("\n") : "No console output"}

⚡ EVENTS TRACKED (${events.length})
━━━━━━━━━━━━━━
${events.length > 0 ? events.slice(0, 20).map((e) => `• ${e.eventType} → ${e.target} → ${e.handler}()`).join("\n") : "No events tracked"}
${events.length > 20 ? `\n... and ${events.length - 20} more events` : ""}

💡 SUGGESTIONS (${suggestions.length})
━━━━━━━━━━━━━━
${suggestions.length > 0 ? suggestions.map((s) => `• [${s.category}] ${s.title}: ${s.description}`).join("\n") : "No suggestions"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by JS Debug Playground
`;

    navigator.clipboard.writeText(report).then(() => {
      toast.success("Debug report copied!", {
        description: "Paste it anywhere to share.",
        duration: 2000,
      });
    });
  }, [state]);

  const handleAIExplain = useCallback(async () => {
    if (!state.code.trim()) {
      toast.error("No code to explain");
      return;
    }
    dispatch({ type: "SET_AI_LOADING", payload: true });
    try {
      const response = await fetch("/api/explain", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          code: state.code,
          context: {
            bugs: state.analysis?.bugs?.map((b) => b.title) || [],
            suggestions: state.analysis?.suggestions?.map((s) => s.title) || [],
          },
        }),
      });
      const data = await response.json();
      if (data.explanation) {
        dispatch({ type: "SET_AI_EXPLANATION", payload: data.explanation });
        toast.success("AI analysis complete!");
      } else {
        throw new Error(data.error || "Failed to get AI explanation");
      }
    } catch (err) {
      toast.error("AI explanation failed", {
        description: err instanceof Error ? err.message : "Check your API key",
      });
    } finally {
      dispatch({ type: "SET_AI_LOADING", payload: false });
    }
  }, [state.code, state.analysis, dispatch]);

  return (
    <header className="flex items-center justify-between px-4 py-2 border-b border-border/50 bg-card/80 backdrop-blur-sm">
      {/* Left: Logo & Title */}
      <div className="flex items-center gap-3">
        <div className="flex items-center gap-2">
          <div className="p-1.5 rounded-md bg-indigo-500/10 border border-indigo-500/20">
            <Braces className="h-4 w-4 text-indigo-400" />
          </div>
          <div>
            <h1 className="text-sm font-bold tracking-tight flex items-center gap-2">
              JS Debug Playground
              <Badge variant="outline" className="text-[9px] font-normal px-1.5 py-0 h-4 border-indigo-500/30 text-indigo-400">
                v1.0
              </Badge>
            </h1>
            <p className="text-[10px] text-muted-foreground -mt-0.5">
              Evaluate &amp; debug AI-generated JavaScript
            </p>
          </div>
        </div>
      </div>

      {/* Right: Actions */}
      <div className="flex items-center gap-2">
        {/* Templates dropdown */}
        <DropdownMenu>
          <DropdownMenuTrigger className="inline-flex items-center justify-center gap-1 whitespace-nowrap rounded-lg text-xs font-medium border border-input bg-background hover:bg-muted hover:text-foreground h-7 px-2.5 cursor-pointer outline-none dark:border-input dark:bg-input/30 dark:hover:bg-input/50">
            <Code2 className="h-3 w-3" />
            Templates
            <ChevronDown className="h-3 w-3" />
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-56">
            <DropdownMenuGroup>
              <DropdownMenuLabel className="text-xs">Sample Code</DropdownMenuLabel>
              <DropdownMenuSeparator />
              {templates.map((template) => (
                <DropdownMenuItem
                  key={template.id}
                  onSelect={() => handleTemplateSelect(template.id)}
                  className="text-xs cursor-pointer"
                >
                  <span className="mr-2">{template.icon}</span>
                  <div>
                    <div className="font-medium">{template.name}</div>
                    <div className="text-muted-foreground text-[10px]">
                      {template.description}
                    </div>
                  </div>
                </DropdownMenuItem>
              ))}
            </DropdownMenuGroup>
          </DropdownMenuContent>
        </DropdownMenu>

        {/* AI Explain */}
        <Button
          variant="ghost"
          size="sm"
          className="h-7 text-xs gap-1 text-muted-foreground hover:text-purple-400"
          onClick={handleAIExplain}
          disabled={state.aiLoading || !state.code.trim()}
        >
          <Sparkles className="h-3 w-3" />
          {state.aiLoading ? "Analyzing..." : "AI Explain"}
        </Button>

        {/* Copy Report */}
        <Button
          variant="ghost"
          size="sm"
          className="h-7 text-xs gap-1 text-muted-foreground hover:text-foreground"
          onClick={handleCopyReport}
          disabled={!state.analysis}
        >
          <ClipboardCopy className="h-3 w-3" />
          Copy Report
        </Button>

        {/* Reset */}
        <Button
          variant="ghost"
          size="sm"
          className="h-7 text-xs gap-1 text-muted-foreground hover:text-foreground"
          onClick={handleReset}
        >
          <RotateCcw className="h-3 w-3" />
          Reset
        </Button>

        {/* Run */}
        <Button
          size="sm"
          className="h-7 text-xs gap-1 bg-emerald-600 hover:bg-emerald-700 text-white transition-colors border border-emerald-500/50"
          onClick={handleRun}
          disabled={state.isRunning}
        >
          {state.isRunning && state.executionStatus === "executing" ? (
            <span className="flex items-center gap-1"><RotateCcw className="h-3 w-3 animate-spin"/> Executing...</span>
          ) : state.isRunning && state.executionStatus === "tracking" ? (
            <span className="flex items-center gap-1"><Activity className="h-3 w-3 animate-pulse"/> Tracking DOM...</span>
          ) : (
            <span className="flex items-center gap-1"><Play className="h-3 w-3" /> Run</span>
          )}
          {!state.isRunning && (
            <kbd className="ml-1 text-[9px] opacity-70 border border-emerald-400/30 rounded px-1">⌘⏎</kbd>
          )}
        </Button>
      </div>
    </header>
  );
}
